/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_des_elections (void)
{
  GtkWidget *gestion_des_elections;
  GtkWidget *fixed1;
  GtkWidget *treeviewge_abir;
  GtkWidget *labelge;
  GtkWidget *entry_recher_abir;
  GtkWidget *supp_abir;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label36;
  GtkWidget *buttongeaffich;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label34;
  GtkWidget *buttonge_modiff;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *buttonge_add;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *btn_to_stat;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label38;
  GtkWidget *btn_Quitter;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label47;
  GtkWidget *recherche_abir;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label37;

  gestion_des_elections = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_des_elections, 850, 550);
  gtk_window_set_title (GTK_WINDOW (gestion_des_elections), _("gestion des elections"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_des_elections), fixed1);

  treeviewge_abir = gtk_tree_view_new ();
  gtk_widget_show (treeviewge_abir);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewge_abir, 124, 110);
  gtk_widget_set_size_request (treeviewge_abir, 684, 234);

  labelge = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Les Elections</b></span>"));
  gtk_widget_show (labelge);
  gtk_fixed_put (GTK_FIXED (fixed1), labelge, 288, 32);
  gtk_widget_set_size_request (labelge, 272, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelge), TRUE);

  entry_recher_abir = gtk_entry_new ();
  gtk_widget_show (entry_recher_abir);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_recher_abir, 408, 440);
  gtk_widget_set_size_request (entry_recher_abir, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_recher_abir), 8226);

  supp_abir = gtk_button_new ();
  gtk_widget_show (supp_abir);
  gtk_fixed_put (GTK_FIXED (fixed1), supp_abir, 144, 360);
  gtk_widget_set_size_request (supp_abir, 100, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (supp_abir), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox9), label36, FALSE, FALSE, 0);

  buttongeaffich = gtk_button_new ();
  gtk_widget_show (buttongeaffich);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongeaffich, 272, 360);
  gtk_widget_set_size_request (buttongeaffich, 100, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttongeaffich), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox8), label34, FALSE, FALSE, 0);

  buttonge_modiff = gtk_button_new ();
  gtk_widget_show (buttonge_modiff);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonge_modiff, 392, 360);
  gtk_widget_set_size_request (buttonge_modiff, 96, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonge_modiff), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  buttonge_add = gtk_button_new ();
  gtk_widget_show (buttonge_add);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonge_add, 512, 360);
  gtk_widget_set_size_request (buttonge_add, 96, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonge_add), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  btn_to_stat = gtk_button_new ();
  gtk_widget_show (btn_to_stat);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_to_stat, 640, 360);
  gtk_widget_set_size_request (btn_to_stat, 105, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (btn_to_stat), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox11), label38, FALSE, FALSE, 0);

  btn_Quitter = gtk_button_new ();
  gtk_widget_show (btn_Quitter);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_Quitter, 40, 496);
  gtk_widget_set_size_request (btn_Quitter, 100, 35);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btn_Quitter), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);

  recherche_abir = gtk_button_new ();
  gtk_widget_show (recherche_abir);
  gtk_fixed_put (GTK_FIXED (fixed1), recherche_abir, 296, 440);
  gtk_widget_set_size_request (recherche_abir, 100, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (recherche_abir), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox10), label37, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeviewge_abir, "row_activated",
                    G_CALLBACK (on_treeviewge_abir_row_activated),
                    NULL);
  g_signal_connect ((gpointer) supp_abir, "clicked",
                    G_CALLBACK (on_supp_abir_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongeaffich, "clicked",
                    G_CALLBACK (on_buttongeaffich_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonge_modiff, "clicked",
                    G_CALLBACK (on_buttonge_modiff_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonge_add, "clicked",
                    G_CALLBACK (on_buttonge_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_to_stat, "clicked",
                    G_CALLBACK (on_btn_to_stat_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Quitter, "clicked",
                    G_CALLBACK (on_btn_Quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) recherche_abir, "clicked",
                    G_CALLBACK (on_recherche_abir_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_elections, gestion_des_elections, "gestion_des_elections");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, treeviewge_abir, "treeviewge_abir");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, labelge, "labelge");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, entry_recher_abir, "entry_recher_abir");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, supp_abir, "supp_abir");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label36, "label36");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, buttongeaffich, "buttongeaffich");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, buttonge_modiff, "buttonge_modiff");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, buttonge_add, "buttonge_add");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, btn_to_stat, "btn_to_stat");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label38, "label38");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, btn_Quitter, "btn_Quitter");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image16, "image16");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label47, "label47");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, recherche_abir, "recherche_abir");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, image11, "image11");
  GLADE_HOOKUP_OBJECT (gestion_des_elections, label37, "label37");

  return gestion_des_elections;
}

GtkWidget*
create_ajouter_election (void)
{
  GtkWidget *ajouter_election;
  GtkWidget *fixed2;
  GtkObject *spin_ge_A_jour_adj;
  GtkWidget *spin_ge_A_jour;
  GtkObject *spin_ge_A_annee_adj;
  GtkWidget *spin_ge_A_annee;
  GtkWidget *entry_GE_A_nbh;
  GtkWidget *entry_GE_A_nbc;
  GtkWidget *labelgeajoutdate;
  GtkWidget *entryy_id;
  GtkWidget *buttonGEAjoutRetour;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label18;
  GtkWidget *buttonGEAjouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label19;
  GtkWidget *labelgeajoutform;
  GtkWidget *comboboxa_abir;
  GtkWidget *labelCheck;
  GtkWidget *combo_muni_abir;
  GtkWidget *labelgeajoutidentif;
  GtkWidget *labelgeajoutm;
  GtkWidget *labelgeajoutnh;
  GtkWidget *labelgeajoutnc;
  GtkWidget *checkBox;

  ajouter_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajouter_election, 900, 550);
  gtk_window_set_title (GTK_WINDOW (ajouter_election), _("ajouter elections"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter_election), fixed2);

  spin_ge_A_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spin_ge_A_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spin_ge_A_jour_adj), 1, 0);
  gtk_widget_show (spin_ge_A_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_ge_A_jour, 264, 416);
  gtk_widget_set_size_request (spin_ge_A_jour, 60, 27);

  spin_ge_A_annee_adj = gtk_adjustment_new (1, 1950, 2022, 1, 10, 10);
  spin_ge_A_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spin_ge_A_annee_adj), 1, 0);
  gtk_widget_show (spin_ge_A_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spin_ge_A_annee, 568, 416);
  gtk_widget_set_size_request (spin_ge_A_annee, 60, 27);

  entry_GE_A_nbh = gtk_entry_new ();
  gtk_widget_show (entry_GE_A_nbh);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_GE_A_nbh, 368, 288);
  gtk_widget_set_size_request (entry_GE_A_nbh, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_GE_A_nbh), 8226);

  entry_GE_A_nbc = gtk_entry_new ();
  gtk_widget_show (entry_GE_A_nbc);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_GE_A_nbc, 368, 328);
  gtk_widget_set_size_request (entry_GE_A_nbc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_GE_A_nbc), 8226);

  labelgeajoutdate = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Date</b></span>"));
  gtk_widget_show (labelgeajoutdate);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgeajoutdate, 160, 416);
  gtk_widget_set_size_request (labelgeajoutdate, 56, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelgeajoutdate), TRUE);

  entryy_id = gtk_entry_new ();
  gtk_widget_show (entryy_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entryy_id, 368, 184);
  gtk_widget_set_size_request (entryy_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryy_id), 8226);

  buttonGEAjoutRetour = gtk_button_new ();
  gtk_widget_show (buttonGEAjoutRetour);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonGEAjoutRetour, 72, 480);
  gtk_widget_set_size_request (buttonGEAjoutRetour, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonGEAjoutRetour), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox3), label18, FALSE, FALSE, 0);

  buttonGEAjouter = gtk_button_new ();
  gtk_widget_show (buttonGEAjouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonGEAjouter, 642, 480);
  gtk_widget_set_size_request (buttonGEAjouter, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonGEAjouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  labelgeajoutform = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Formulaire d'ajout d'une election</b></span>"));
  gtk_widget_show (labelgeajoutform);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgeajoutform, 176, 24);
  gtk_widget_set_size_request (labelgeajoutform, 496, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelgeajoutform), TRUE);

  comboboxa_abir = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxa_abir);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxa_abir, 360, 416);
  gtk_widget_set_size_request (comboboxa_abir, 168, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxa_abir), _("mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxa_abir), _("avril "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxa_abir), _("mai"));

  labelCheck = gtk_label_new ("");
  gtk_widget_show (labelCheck);
  gtk_fixed_put (GTK_FIXED (fixed2), labelCheck, 328, 472);
  gtk_widget_set_size_request (labelCheck, 250, 30);

  combo_muni_abir = gtk_combo_box_new_text ();
  gtk_widget_show (combo_muni_abir);
  gtk_fixed_put (GTK_FIXED (fixed2), combo_muni_abir, 368, 240);
  gtk_widget_set_size_request (combo_muni_abir, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_muni_abir), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_muni_abir), _("Bardo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_muni_abir), _("Beja"));

  labelgeajoutidentif = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Identifiant</b></span>"));
  gtk_widget_show (labelgeajoutidentif);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgeajoutidentif, 224, 176);
  gtk_widget_set_size_request (labelgeajoutidentif, 128, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelgeajoutidentif), TRUE);

  labelgeajoutm = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Municipalite</b></span>"));
  gtk_widget_show (labelgeajoutm);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgeajoutm, 200, 240);
  gtk_widget_set_size_request (labelgeajoutm, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelgeajoutm), TRUE);

  labelgeajoutnh = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Nombre d'habitants</b></span>"));
  gtk_widget_show (labelgeajoutnh);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgeajoutnh, 184, 280);
  gtk_widget_set_size_request (labelgeajoutnh, 168, 40);
  gtk_label_set_use_markup (GTK_LABEL (labelgeajoutnh), TRUE);

  labelgeajoutnc = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Nombres des conseillers</b></span>"));
  gtk_widget_show (labelgeajoutnc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelgeajoutnc, 168, 328);
  gtk_widget_set_size_request (labelgeajoutnc, 184, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelgeajoutnc), TRUE);

  checkBox = gtk_check_button_new_with_mnemonic (_("D'accord !"));
  gtk_widget_show (checkBox);
  gtk_fixed_put (GTK_FIXED (fixed2), checkBox, 664, 416);
  gtk_widget_set_size_request (checkBox, 118, 24);

  g_signal_connect ((gpointer) buttonGEAjoutRetour, "clicked",
                    G_CALLBACK (on_buttonGEAjoutRetour_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGEAjouter, "clicked",
                    G_CALLBACK (on_buttonGEAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkBox, "toggled",
                    G_CALLBACK (on_checkBox_toggled),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (labelgeajoutdate), spin_ge_A_jour);
  gtk_label_set_mnemonic_widget (GTK_LABEL (labelgeajoutnh), entry_GE_A_nbh);
  gtk_label_set_mnemonic_widget (GTK_LABEL (labelgeajoutnc), entry_GE_A_nbc);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_election, ajouter_election, "ajouter_election");
  GLADE_HOOKUP_OBJECT (ajouter_election, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter_election, spin_ge_A_jour, "spin_ge_A_jour");
  GLADE_HOOKUP_OBJECT (ajouter_election, spin_ge_A_annee, "spin_ge_A_annee");
  GLADE_HOOKUP_OBJECT (ajouter_election, entry_GE_A_nbh, "entry_GE_A_nbh");
  GLADE_HOOKUP_OBJECT (ajouter_election, entry_GE_A_nbc, "entry_GE_A_nbc");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelgeajoutdate, "labelgeajoutdate");
  GLADE_HOOKUP_OBJECT (ajouter_election, entryy_id, "entryy_id");
  GLADE_HOOKUP_OBJECT (ajouter_election, buttonGEAjoutRetour, "buttonGEAjoutRetour");
  GLADE_HOOKUP_OBJECT (ajouter_election, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ajouter_election, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ajouter_election, image4, "image4");
  GLADE_HOOKUP_OBJECT (ajouter_election, label18, "label18");
  GLADE_HOOKUP_OBJECT (ajouter_election, buttonGEAjouter, "buttonGEAjouter");
  GLADE_HOOKUP_OBJECT (ajouter_election, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ajouter_election, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ajouter_election, image5, "image5");
  GLADE_HOOKUP_OBJECT (ajouter_election, label19, "label19");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelgeajoutform, "labelgeajoutform");
  GLADE_HOOKUP_OBJECT (ajouter_election, comboboxa_abir, "comboboxa_abir");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelCheck, "labelCheck");
  GLADE_HOOKUP_OBJECT (ajouter_election, combo_muni_abir, "combo_muni_abir");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelgeajoutidentif, "labelgeajoutidentif");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelgeajoutm, "labelgeajoutm");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelgeajoutnh, "labelgeajoutnh");
  GLADE_HOOKUP_OBJECT (ajouter_election, labelgeajoutnc, "labelgeajoutnc");
  GLADE_HOOKUP_OBJECT (ajouter_election, checkBox, "checkBox");

  return ajouter_election;
}

GtkWidget*
create_modifier_election (void)
{
  GtkWidget *modifier_election;
  GtkWidget *fixed3;
  GtkObject *spinm_jour_adj;
  GtkWidget *spinm_jour;
  GtkObject *spinm_annee_adj;
  GtkWidget *spinm_annee;
  GtkWidget *entrym_nbhabitant;
  GtkWidget *entrygem_nbcons;
  GtkWidget *labelgemodiffnc;
  GtkWidget *labelgemodiffnh;
  GtkWidget *labelgemodiffm;
  GtkWidget *labelgemodiffdate;
  GtkWidget *labelgemodiffidentif;
  GtkWidget *label35;
  GtkWidget *combobox2_abir;
  GtkWidget *comboboxm_mois;
  GtkWidget *buttonGEModifRetour;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label33;
  GtkWidget *buttonmod_abir;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label32;

  modifier_election = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier_election, 850, 550);
  gtk_window_set_title (GTK_WINDOW (modifier_election), _("modifier election"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier_election), fixed3);

  spinm_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinm_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinm_jour_adj), 1, 0);
  gtk_widget_show (spinm_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), spinm_jour, 384, 384);
  gtk_widget_set_size_request (spinm_jour, 60, 27);

  spinm_annee_adj = gtk_adjustment_new (1, 1950, 2022, 1, 10, 10);
  spinm_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinm_annee_adj), 1, 0);
  gtk_widget_show (spinm_annee);
  gtk_fixed_put (GTK_FIXED (fixed3), spinm_annee, 624, 384);
  gtk_widget_set_size_request (spinm_annee, 60, 27);

  entrym_nbhabitant = gtk_entry_new ();
  gtk_widget_show (entrym_nbhabitant);
  gtk_fixed_put (GTK_FIXED (fixed3), entrym_nbhabitant, 416, 256);
  gtk_widget_set_size_request (entrym_nbhabitant, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrym_nbhabitant), 8226);

  entrygem_nbcons = gtk_entry_new ();
  gtk_widget_show (entrygem_nbcons);
  gtk_fixed_put (GTK_FIXED (fixed3), entrygem_nbcons, 416, 304);
  gtk_widget_set_size_request (entrygem_nbcons, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygem_nbcons), 8226);

  labelgemodiffnc = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Nombre des conseillers</b></span>"));
  gtk_widget_show (labelgemodiffnc);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemodiffnc, 176, 288);
  gtk_widget_set_size_request (labelgemodiffnc, 208, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelgemodiffnc), TRUE);

  labelgemodiffnh = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Nombre d'habitants</b></span>"));
  gtk_widget_show (labelgemodiffnh);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemodiffnh, 208, 240);
  gtk_widget_set_size_request (labelgemodiffnh, 168, 48);
  gtk_label_set_use_markup (GTK_LABEL (labelgemodiffnh), TRUE);

  labelgemodiffm = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Municipalite</b></span>"));
  gtk_widget_show (labelgemodiffm);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemodiffm, 208, 192);
  gtk_widget_set_size_request (labelgemodiffm, 168, 48);
  gtk_label_set_use_markup (GTK_LABEL (labelgemodiffm), TRUE);

  labelgemodiffdate = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Date</b></span>"));
  gtk_widget_show (labelgemodiffdate);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemodiffdate, 248, 384);
  gtk_widget_set_size_request (labelgemodiffdate, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelgemodiffdate), TRUE);

  labelgemodiffidentif = gtk_label_new_with_mnemonic (_("<span foreground=\"black\"><b>Identifiant</b></span>"));
  gtk_widget_show (labelgemodiffidentif);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemodiffidentif, 152, 128);
  gtk_widget_set_size_request (labelgemodiffidentif, 272, 56);
  gtk_label_set_use_markup (GTK_LABEL (labelgemodiffidentif), TRUE);

  label35 = gtk_label_new ("");
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 424, 128);
  gtk_widget_set_size_request (label35, 144, 49);

  combobox2_abir = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2_abir);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox2_abir, 416, 200);
  gtk_widget_set_size_request (combobox2_abir, 176, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_abir), _("tunis "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_abir), _("beja"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_abir), _("sfax"));

  comboboxm_mois = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxm_mois);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxm_mois, 464, 384);
  gtk_widget_set_size_request (comboboxm_mois, 128, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm_mois), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm_mois), _("Avril "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm_mois), _("Mai"));

  buttonGEModifRetour = gtk_button_new ();
  gtk_widget_show (buttonGEModifRetour);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGEModifRetour, 32, 488);
  gtk_widget_set_size_request (buttonGEModifRetour, 112, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonGEModifRetour), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox7), label33, FALSE, FALSE, 0);

  buttonmod_abir = gtk_button_new ();
  gtk_widget_show (buttonmod_abir);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonmod_abir, 648, 496);
  gtk_widget_set_size_request (buttonmod_abir, 120, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonmod_abir), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox6), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonGEModifRetour, "clicked",
                    G_CALLBACK (on_buttonGEModifRetour_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmod_abir, "clicked",
                    G_CALLBACK (on_buttonmod_abir_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (labelgemodiffdate), spinm_jour);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_election, modifier_election, "modifier_election");
  GLADE_HOOKUP_OBJECT (modifier_election, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier_election, spinm_jour, "spinm_jour");
  GLADE_HOOKUP_OBJECT (modifier_election, spinm_annee, "spinm_annee");
  GLADE_HOOKUP_OBJECT (modifier_election, entrym_nbhabitant, "entrym_nbhabitant");
  GLADE_HOOKUP_OBJECT (modifier_election, entrygem_nbcons, "entrygem_nbcons");
  GLADE_HOOKUP_OBJECT (modifier_election, labelgemodiffnc, "labelgemodiffnc");
  GLADE_HOOKUP_OBJECT (modifier_election, labelgemodiffnh, "labelgemodiffnh");
  GLADE_HOOKUP_OBJECT (modifier_election, labelgemodiffm, "labelgemodiffm");
  GLADE_HOOKUP_OBJECT (modifier_election, labelgemodiffdate, "labelgemodiffdate");
  GLADE_HOOKUP_OBJECT (modifier_election, labelgemodiffidentif, "labelgemodiffidentif");
  GLADE_HOOKUP_OBJECT (modifier_election, label35, "label35");
  GLADE_HOOKUP_OBJECT (modifier_election, combobox2_abir, "combobox2_abir");
  GLADE_HOOKUP_OBJECT (modifier_election, comboboxm_mois, "comboboxm_mois");
  GLADE_HOOKUP_OBJECT (modifier_election, buttonGEModifRetour, "buttonGEModifRetour");
  GLADE_HOOKUP_OBJECT (modifier_election, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_election, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_election, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifier_election, label33, "label33");
  GLADE_HOOKUP_OBJECT (modifier_election, buttonmod_abir, "buttonmod_abir");
  GLADE_HOOKUP_OBJECT (modifier_election, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (modifier_election, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifier_election, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifier_election, label32, "label32");

  return modifier_election;
}

GtkWidget*
create_Statistique (void)
{
  GtkWidget *Statistique;
  GtkWidget *fixedstat;
  GtkWidget *entry_idL_nbe;
  GtkWidget *label_R_tpe;
  GtkWidget *btn_calculer_nbe;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label40;
  GtkWidget *btn_Calculer_tpe;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label44;
  GtkWidget *labelids;
  GtkWidget *labeltpe;
  GtkWidget *labeltphf;
  GtkWidget *labelf;
  GtkWidget *labelh;
  GtkWidget *label_R_homme;
  GtkWidget *label_femme;
  GtkWidget *btn_Calculer_tphf;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label46;
  GtkWidget *label_R_nbe;
  GtkWidget *btn_Retour_stat;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image17;
  GtkWidget *label48;

  Statistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Statistique, 900, 550);
  gtk_window_set_title (GTK_WINDOW (Statistique), _("Statistique"));

  fixedstat = gtk_fixed_new ();
  gtk_widget_show (fixedstat);
  gtk_container_add (GTK_CONTAINER (Statistique), fixedstat);

  entry_idL_nbe = gtk_entry_new ();
  gtk_widget_show (entry_idL_nbe);
  gtk_fixed_put (GTK_FIXED (fixedstat), entry_idL_nbe, 320, 88);
  gtk_widget_set_size_request (entry_idL_nbe, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idL_nbe), 8226);

  label_R_tpe = gtk_label_new ("");
  gtk_widget_show (label_R_tpe);
  gtk_fixed_put (GTK_FIXED (fixedstat), label_R_tpe, 568, 192);
  gtk_widget_set_size_request (label_R_tpe, 100, 25);

  btn_calculer_nbe = gtk_button_new ();
  gtk_widget_show (btn_calculer_nbe);
  gtk_fixed_put (GTK_FIXED (fixedstat), btn_calculer_nbe, 504, 80);
  gtk_widget_set_size_request (btn_calculer_nbe, 100, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (btn_calculer_nbe), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox12), label40, FALSE, FALSE, 0);

  btn_Calculer_tpe = gtk_button_new ();
  gtk_widget_show (btn_Calculer_tpe);
  gtk_fixed_put (GTK_FIXED (fixedstat), btn_Calculer_tpe, 176, 183);
  gtk_widget_set_size_request (btn_Calculer_tpe, 100, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (btn_Calculer_tpe), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox13), label44, FALSE, FALSE, 0);

  labelids = gtk_label_new (_("Donner l'identifiant de BV :"));
  gtk_widget_show (labelids);
  gtk_fixed_put (GTK_FIXED (fixedstat), labelids, 64, 88);
  gtk_widget_set_size_request (labelids, 250, 25);

  labeltpe = gtk_label_new (_("Taux de participation par electeur :"));
  gtk_widget_show (labeltpe);
  gtk_fixed_put (GTK_FIXED (fixedstat), labeltpe, 280, 192);
  gtk_widget_set_size_request (labeltpe, 250, 25);

  labeltphf = gtk_label_new (_("Taux de participation homme et femme :"));
  gtk_widget_show (labeltphf);
  gtk_fixed_put (GTK_FIXED (fixedstat), labeltphf, 280, 272);
  gtk_widget_set_size_request (labeltphf, 300, 25);

  labelf = gtk_label_new (_("Femme"));
  gtk_widget_show (labelf);
  gtk_fixed_put (GTK_FIXED (fixedstat), labelf, 592, 296);
  gtk_widget_set_size_request (labelf, 100, 25);

  labelh = gtk_label_new (_("Homme"));
  gtk_widget_show (labelh);
  gtk_fixed_put (GTK_FIXED (fixedstat), labelh, 592, 248);
  gtk_widget_set_size_request (labelh, 100, 25);

  label_R_homme = gtk_label_new ("");
  gtk_widget_show (label_R_homme);
  gtk_fixed_put (GTK_FIXED (fixedstat), label_R_homme, 720, 248);
  gtk_widget_set_size_request (label_R_homme, 100, 25);

  label_femme = gtk_label_new ("");
  gtk_widget_show (label_femme);
  gtk_fixed_put (GTK_FIXED (fixedstat), label_femme, 728, 296);
  gtk_widget_set_size_request (label_femme, 100, 25);

  btn_Calculer_tphf = gtk_button_new ();
  gtk_widget_show (btn_Calculer_tphf);
  gtk_fixed_put (GTK_FIXED (fixedstat), btn_Calculer_tphf, 178, 266);
  gtk_widget_set_size_request (btn_Calculer_tphf, 100, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btn_Calculer_tphf), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox14), label46, FALSE, FALSE, 0);

  label_R_nbe = gtk_label_new ("");
  gtk_widget_show (label_R_nbe);
  gtk_fixed_put (GTK_FIXED (fixedstat), label_R_nbe, 632, 88);
  gtk_widget_set_size_request (label_R_nbe, 100, 29);

  btn_Retour_stat = gtk_button_new ();
  gtk_widget_show (btn_Retour_stat);
  gtk_fixed_put (GTK_FIXED (fixedstat), btn_Retour_stat, 104, 456);
  gtk_widget_set_size_request (btn_Retour_stat, 100, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (btn_Retour_stat), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox16), image17, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox16), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btn_calculer_nbe, "clicked",
                    G_CALLBACK (on_btn_calculer_nbe_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Calculer_tpe, "clicked",
                    G_CALLBACK (on_btn_Calculer_tpe_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Calculer_tphf, "clicked",
                    G_CALLBACK (on_btn_Calculer_tphf_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_Retour_stat, "clicked",
                    G_CALLBACK (on_btn_Retour_stat_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Statistique, Statistique, "Statistique");
  GLADE_HOOKUP_OBJECT (Statistique, fixedstat, "fixedstat");
  GLADE_HOOKUP_OBJECT (Statistique, entry_idL_nbe, "entry_idL_nbe");
  GLADE_HOOKUP_OBJECT (Statistique, label_R_tpe, "label_R_tpe");
  GLADE_HOOKUP_OBJECT (Statistique, btn_calculer_nbe, "btn_calculer_nbe");
  GLADE_HOOKUP_OBJECT (Statistique, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Statistique, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Statistique, image13, "image13");
  GLADE_HOOKUP_OBJECT (Statistique, label40, "label40");
  GLADE_HOOKUP_OBJECT (Statistique, btn_Calculer_tpe, "btn_Calculer_tpe");
  GLADE_HOOKUP_OBJECT (Statistique, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Statistique, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Statistique, image14, "image14");
  GLADE_HOOKUP_OBJECT (Statistique, label44, "label44");
  GLADE_HOOKUP_OBJECT (Statistique, labelids, "labelids");
  GLADE_HOOKUP_OBJECT (Statistique, labeltpe, "labeltpe");
  GLADE_HOOKUP_OBJECT (Statistique, labeltphf, "labeltphf");
  GLADE_HOOKUP_OBJECT (Statistique, labelf, "labelf");
  GLADE_HOOKUP_OBJECT (Statistique, labelh, "labelh");
  GLADE_HOOKUP_OBJECT (Statistique, label_R_homme, "label_R_homme");
  GLADE_HOOKUP_OBJECT (Statistique, label_femme, "label_femme");
  GLADE_HOOKUP_OBJECT (Statistique, btn_Calculer_tphf, "btn_Calculer_tphf");
  GLADE_HOOKUP_OBJECT (Statistique, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Statistique, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Statistique, image15, "image15");
  GLADE_HOOKUP_OBJECT (Statistique, label46, "label46");
  GLADE_HOOKUP_OBJECT (Statistique, label_R_nbe, "label_R_nbe");
  GLADE_HOOKUP_OBJECT (Statistique, btn_Retour_stat, "btn_Retour_stat");
  GLADE_HOOKUP_OBJECT (Statistique, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Statistique, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Statistique, image17, "image17");
  GLADE_HOOKUP_OBJECT (Statistique, label48, "label48");

  return Statistique;
}

