/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_des_elections (void);
GtkWidget* create_ajouter_election (void);
GtkWidget* create_modifier_election (void);
GtkWidget* create_Statistique (void);
